### PR TITLE
[Feature] Added stats section to analysis charts

### PR DESCRIPTION
**Pull request by alexmalinin**
## Ticket:
- https://www.pivotaltracker.com/story/show/166697008

## Result:
- added min, max, standard deviation stats to the bottom of the charts
- added units to chart, parsing from legend

### CODE REVIEW

**Comment by davidsingal** [comment]
We added `unit` field in legend config. And we removed the unit in `min`, `max` and `mid`. Could you check if we have to add this unit in other places more?

**Comment by alexmalinin** [comment]
> We added `unit` field in legend config. And we removed the unit in `min`, `max` and `mid`. Could you check if we have to add this unit in other places more?

image
The data now looks bit unsolid
And `Total annual rainfall` layer is have analysis chart too, but units still included in values

**Comment by davidsingal** [comment]
Yeah.. this will happen meanwhile we are migrating every layer to use `unit`.

**Comment by alexmalinin** [comment]
> Yeah.. this will happen meanwhile we are migrating every layer to use `unit`.

Okay, got it!

**Pull request merged**
